package common;

import java.io.Serializable;

/**
 * The Reservation class represents a data transfer object (DTO) for restaurant bookings.
 * It encapsulates all necessary information for a reservation and is designed to be
 * sent across the network between the Client and Server using OCSF.
 * * <p>Implements {@link Serializable} to allow object streaming over socket connections.</p>
 * * @author Software Engineering Student
 * @version 1.0
 */
public class Reservation implements Serializable {
    
    /**
     * Serial version ID for ensuring compatibility during the serialization process.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Enum representing the various states a reservation can hold within the system logic.
     */
    public enum ReservationStatus {
        /** Reservation is confirmed and active in the system. */
        ACTIVE, 
        /** Reservation was revoked by the user or the system. */
        CANCELED, 
        /** the customer arrived to the restaurant. */
        ARRIVED
    }

    /** * Unique identifier for the reservation, typically generated by the Database.
     * Maps to BIGINT in MySQL.
     */
    private long confirmationCode;   

    /** * The date and time for the booking in 'YYYY-MM-DD HH:MM:SS' format.
     * Maps to DATETIME in MySQL.
     */
    private String reservationDateTime; 

    /** * Total count of people expected for this booking.
     * Maps to INT in MySQL.
     */
    private int numberOfGuests;      

    /** * The unique ID of the user (Subscriber or Occasional) who made the booking.
     * Maps to INT in MySQL.
     */
    private int userId;              

    /** * The current lifecycle status of the reservation.
     */
    private ReservationStatus status;

    /**
     * Constructs a new Reservation instance with mandatory fields.
     * The status is initialized to ACTIVE by default.
     *
     * @param userId The ID of the customer making the reservation.
     * @param dateTime The scheduled date and time for the booking.
     * @param numberOfGuests Total number of attendees.
     */
    public Reservation(int userId, String dateTime, int numberOfGuests) {
        this.userId = userId;
        this.reservationDateTime = dateTime;
        this.numberOfGuests = numberOfGuests;
        this.status = ReservationStatus.ACTIVE; 
    }

    /**
     * @return The unique confirmation code assigned to this reservation.
     */
    public long getConfirmationCode() { 
        return confirmationCode; 
    }

    /**
     * Sets the confirmation code, usually after retrieving it from the DB (Generated Keys).
     * @param code The numeric confirmation code to set.
     */
    public void setConfirmationCode(long code) { 
        this.confirmationCode = code; 
    }
    
    /**
     * Updates the current status of the reservation.
     *
     * @param status the new reservation status as defined in ReservationStatus
     */
    public void setStatus(ReservationStatus status) {
        this.status = status;
    }

    /**
     * @return The scheduled date and time string.
     */
    public String getReservationDateTime() { 
        return reservationDateTime; 
    }
    
    /**
     * Extracts the date part from the reservation date-time string.
     *
     * @return the reservation date in YYYY-MM-DD format
     */
    public String getReservationDate() {
        if (reservationDateTime == null) return "";
        return reservationDateTime.split(" ")[0]; // YYYY-MM-DD
    }

    /**
     * Extracts the time part from the reservation date-time string.
     *
     * @return the reservation time in HH:MM:SS format
     */
    public String getReservationTime() {
        if (reservationDateTime == null) return "";
        return reservationDateTime.split(" ")[1]; // HH:MM:SS
    }

    /**
     * @return The number of guests included in this booking.
     */
    public int getNumberOfGuests() { 
        return numberOfGuests; 
    }

    /**
     * @return The user ID associated with this reservation.
     */
    public int getUserId() { 
        return userId; 
    }

    /**
     * Converts the enum status to a string format for logging or DB storage.
     * @return String representation of the current {@link ReservationStatus}.
     */
    public String getStatusString() { 
        return status.name(); 
    }
}