package client;

import java.io.IOException;
import common.ChatIF;
import ocsf.client.AbstractClient;

/**
 * The ChatClient class represents the logical part of the client
 * in the OCSF architecture.  
 * 
 * Responsibilities:
 * - Receive messages from the server and forward them to the UI.
 * - Receive messages from the UI and send them to the server.
 * 
 * This class extends AbstractClient, which provides:
 * openConnection(), sendToServer(), closeConnection(), etc.
 */
public class ChatClient extends AbstractClient {

    /**
     * A reference to the UI (GUI or text-based).
     * Any class that implements ChatIF can serve as the UI layer.
     */
    private ChatIF clientUI;


    /**
     * Creates a new ChatClient instance.
     *
     * @param host    The server's IP address or hostname.
     * @param port    The port number of the server.
     * @param clientUI The UI object used to display messages.
     *
     * After construction, the client immediately attempts to open a connection.
     *
     * @throws IOException if the connection to the server fails.
     */
    public ChatClient(String host, int port, ChatIF clientUI) throws IOException {
        super(host, port);   // Pass host and port to the OCSF framework
        this.clientUI = clientUI;
        openConnection();    // Attempt to connect immediately
    }


    /**
     * Handles any message received from the server.
     * This method is automatically called by the OCSF framework.
     *
     * @param msg The message sent by the server.
     */
    @Override
    public void handleMessageFromServer(Object msg) {
        clientUI.display(msg);  // Forward message to the UI
    }


    /**
     * Sends a message from the UI to the server.
     *
     * @param message The message generated by the UI.
     */
    public void handleMessageFromClientUI(Object message) {
        try {
            sendToServer(message);  // Physical send via OCSF
        } catch (IOException e) {
            clientUI.display("Could not send message to server. Terminating client.");
            quit();
        }
    }


    /**
     * Terminates the client by closing the connection
     * and exiting the application.
     */
    public void quit() {
        try {
            closeConnection();
        } catch (IOException e) {
            // Not critical on quit
        }
        System.exit(0);
    }
}
