package clientGUI;

import client.ChatClient;
import clientGUI.Controllers.RemoteLoginController;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * Main entry point for the Bistro Remote Access client application.
 * This class is responsible for launching the JavaFX environment, initializing the
 * primary user interface, and establishing the initial OCSF network connection.
 * * Responsibilities:
 * 1. Bootstrapping the JavaFX application lifecycle.
 * 2. Loading and displaying the initial FXML layout (Login Frame).
 * 3. Initializing the {@link ChatClient} to enable server communication.
 * 4. Linking the Client logic with the UI Controller (Dependency Injection).
 * * @author Software Engineering Student
 * @version 1.0
 */
public class RemoteClientUI extends Application {
    
    /** * The persistent network client instance. 
     * It remains alive throughout the application lifecycle to handle socket communication.
     */
    private ChatClient client;

    /**
     * Standard main method that launches the JavaFX Application thread.
     * @param args Command-line arguments.
     */
    public static void main(String[] args) {
        launch(args);
    }

    /**
     * The main entry point for all JavaFX applications. 
     * This method is called after the system is ready for the application to begin running.
     *
     * @param primaryStage The primary stage (window) for this application.
     * @throws Exception If there is an issue loading FXML resources or initializing the client.
     */
    @Override
    public void start(Stage primaryStage) throws Exception {
        
        // --- UI Initialization Phase ---
        
        // Load the FXML file for the initial Remote Login screen
        FXMLLoader loader = new FXMLLoader(getClass().getResource("fxmlFiles/RemoteLoginFrame.fxml"));
        Parent root = loader.load();
        
        // Obtain the controller instance generated by the FXMLLoader
        RemoteLoginController controller = loader.getController();

        // Configure the Primary Stage (Application Window)
        Scene scene = new Scene(root);
        primaryStage.setTitle("Bistro - Remote Access Portal");
        
        // Prevent window resizing to maintain the designed UI layout integrity
        primaryStage.setResizable(false);
        primaryStage.setScene(scene);
        primaryStage.show();

        // --- Network Initialization Phase ---

        try {
            /**
             * Initialize the ChatClient.
             * Hardcoded for 'localhost' on port 5555. 
             * In a production environment, these parameters could be loaded from a config file.
             */
            client = new ChatClient("localhost", 5555, controller);
            
            /**
             * Dependency Injection: 
             * Injecting the initialized network client into the UI controller.
             * This allows the controller to trigger 'sendToServer' calls based on user actions.
             */
            controller.setClient(client);
            
            // Log successful connection to the internal UI Logger
            controller.appendLog("Connected to server successfully.");
            
        } catch (Exception e) {
            /**
             * Graceful Degradation:
             * If the server is unreachable (Offline), notify the user through the UI 
             * and print the stack trace for developer debugging.
             */
            if (controller != null) {
                controller.appendLog("Status: Offline - Connection Failed.");
            }
            e.printStackTrace();
        }
    }
}